export const profile = {
  name: "Lingyu Peng",
  chineseName: "彭凌钰",
  title: "Master's Student in Industrial Design",
  school: "Future Design School",
  university: "Harbin Institute of Technology (Shenzhen)",
  location: "Shenzhen, China",
  email: "lingyupeng6@163.com",
  portrait: "portfolio/portrait.png",
  drawnPortrait: "portfolio/drawn-avatar.png",
  bio: [
    "I am a Master's student in Industrial Design at the Future Design School, Harbin Institute of Technology (Shenzhen), advised by Associate Professor Qingchuan Li. I received my B.Eng. in Industrial Design from the University of Science and Technology Beijing, where I worked with Professor Xiaohui Wang.",
    "My research is situated at the intersection of human-computer interaction (HCI) and design, with a focus on how generative AI and emerging interactive systems reshape creative practice, user agency, and cultural participation. I combine empirical HCI research with research-through-design to study how people interact, collaborate, and create with computational systems in creative and cultural contexts.",
    "One strand of my research explores how archives, cultural heritage, and social memory can be transformed into interactive experiences that invite public participation. I am particularly interested in how generative AI can enable people to engage with cultural materials through creation, interpretation, learning, and reflection.",
    "Another strand examines human–AI interaction, focusing on how users navigate AI-supported creative and design processes and what forms of support they need, including intent alignment, design guidance, agent role design, and process transparency.",
  ],
  advisors: [
    {
      name: "Associate Professor Qingchuan Li",
      href: "https://scholar.hit.edu.cn/en/persons/qingchuan-li/",
    },
    {
      name: "Professor Xiaohui Wang",
      href: "https://faculty.ustb.edu.cn/XiaohuiWang11/en/lwcg/98230/list/index.htm",
    },
  ],
  links: [
    {
      label: "Google Scholar",
      href: "https://scholar.google.com/citations?hl=en&user=5340u2gAAAAJ",
    },
    { label: "GitHub", href: "https://github.com/lingyupeng" },
    {
      label: "Design Portfolio",
      href: "https://yu-s-design-portfolio-352331414026.us-west1.run.app",
    },
    { label: "CV", href: "lingyu-peng-cv.pdf" },
  ],
};

export const moreAboutMe = [
  "The name “Yu” comes from the third character of my Chinese name, “钰”, a character associated with treasure and hard metal, carrying the meanings of preciousness and resilience.",
  "“钰，宝也。——《五音集韵》；钰，坚金。——《玉篇》”",
  "Since 2021, I have been on a journey through design and human-computer interaction. Along the way, I have kept exploring, learning, and shaping myself through practice. Gradually, I have felt myself growing closer to what this character represents: something gentle yet strong, something precious yet enduring.",
  "I cherish every idea I have created and every effort I have made. This website is a way of holding them all together.",
];

export const publications = [
  {
    id: "R01",
    category: "Research Papers",
    year: "2026",
    date: "2026-09",
    displayDate: "Sep 2026",
    title: "The Dynamics of Human–AI Co-Creation: An Investigation of Design Tensions in Cultural and Creative Design Through a Case of Yanchuan Patchwork",
    authors: "Lingyu Peng, Yuanlinxi Li, Bai Xue, Zihang Zhang, and Qingchuan Li",
    venue: "International Journal of Human-Computer Interaction, JCR Q1, 2026",
    links: [
      { label: "Paper", href: "https://www.tandfonline.com/doi/full/10.1080/10447318.2026.2726090" },
    ],
    teaser: "papers/ijhci.png",
    teaserLabel: "Human–AI\nCo-Creation",
    teaserTone: "klein",
    keywords: ["Human–AI co-creation", "Generative AI", "Design tensions", "Cultural heritage"],
    abstract: "This study examines the tensions that arise when generative AI participates in cultural and creative design. Drawing on Yanchuan Patchwork workshops and expert interviews, it identifies recurring decision-making tensions and explains how changing knowledge, processes, roles, and resource allocation shape human–AI co-creation.",
    featured: true,
  },
  {
    id: "R02",
    category: "Research Papers",
    year: "2025",
    date: "2025-05",
    displayDate: "May 2025",
    title: "Roles and Contributions of Cultural Heritage Professionals in AI-Assisted Cultural Heritage Design Workflows: A Case Study of Yanchuan Patchwork",
    authors: "Lingyu Peng, Yuanlinxi Li, Bai Xue, Jiaxin Zhang, and Qingchuan Li",
    venue: "Culture and Computing, HCII 2025, LNCS 15800, Springer, 2025",
    links: [
      { label: "Paper", href: "https://link.springer.com/chapter/10.1007/978-3-031-93160-4_4" },
    ],
    teaser: "papers/hcii.png",
    teaserLabel: "Heritage\nProfessionals",
    teaserTone: "sky",
    keywords: ["AIGC", "Cultural heritage", "Heritage professionals", "AI-assisted design"],
    abstract: "A workshop on Yanchuan Patchwork is used to investigate how cultural heritage professionals contribute to AI-assisted design. The study identifies their roles as cultural consultants, data providers and creators, and reviewers and evaluators, while emphasizing the need for continuous involvement and clearer collaboration across the workflow.",
    featured: true,
  },
  {
    id: "R03",
    category: "Research Papers",
    year: "2025",
    date: "2025-04",
    displayDate: "Apr 2025",
    title: "More Than Beautiful: Exploring Design Features, Practical Perspectives, and Implications of Artistic Data Visualization",
    authors: "Xingyu Lan, Yifan Wang, Lingyu Peng, and Xiaofan Ma",
    venue: "IEEE Pacific Visualization Conference, 2025. Best Paper Award",
    links: [
      { label: "Paper", href: "https://ieeexplore.ieee.org/abstract/document/11021080/" },
    ],
    teaser: "papers/pacificvis.png",
    teaserLabel: "Artistic Data\nVisualization",
    teaserTone: "grid",
    keywords: ["Artistic visualization", "Design taxonomy", "Data art", "Artist interviews"],
    abstract: "Through an analysis of 220 data artworks and interviews with twelve data artists, this work characterizes the design techniques, intentions, and practical challenges of artistic data visualization. It develops a taxonomy spanning sensation, interaction, narrative, and physicality, and proposes directions for future visualization research.",
    featured: true,
  },
  {
    id: "R04",
    category: "Research Papers",
    year: "2023",
    date: "2023-12",
    displayDate: "Dec 2023",
    titleZh: "AIGC中式美学文创设计研究",
    title: "Cultural and Creative Design of AIGC Chinese Aesthetic",
    authors: "Yu Song, Xiaosong Qian, Lingyu Peng, Zihan Ye, and Jingyan Qing",
    venue: "Packaging Engineering, 44(24), 2023. Chinese Core Journal",
    links: [
      { label: "Paper", href: "https://doi.org/10.19554/j.cnki.1001-3563.2023.24.001" },
    ],
    teaser: "papers/packaging-engineering.png",
    teaserLabel: "AIGC ×\nChinese Aesthetics",
    teaserTone: "ink",
    keywords: ["AIGC", "Chinese aesthetics", "Ink painting", "Cultural product design"],
    abstract: "本研究以中国水墨画为对象，探索从传统美学素材到 AIGC 文创产品的转化路径。研究结合显著性检测、图像分割与扩散模型训练，以齐白石“蟹”系列为例验证传统绘画特征提取、生成与衍生设计的可行性。",
  },
  {
    id: "A01",
    category: "Art Papers",
    year: "2026",
    date: "2026-12",
    displayDate: "Dec 2026",
    title: "Reflecting on Future Human-AI Society through Along the River During the Qingming Festival",
    authors: "Lingyu Peng, RAY LC, Yuhao He, and Qingchuan Li",
    venue: "Forthcoming · SIGGRAPH Asia 2026 Art Papers · December 2026",
    links: [],
    teaser: "papers/siggraph-asia.png",
    teaserLabel: "Qingming\nFuture Society",
    teaserTone: "river",
    keywords: ["Human–AI society", "Cultural heritage", "Generative art", "Interactive art"],
    abstract: "This art paper uses Along the River During the Qingming Festival as a cultural lens for reflecting on a future human–AI society. The work connects historical everyday life with contemporary generative systems to invite discussion about agency, coexistence, and social change.",
  },
  {
    id: "A02",
    category: "Art Papers",
    year: "2026",
    date: "2026-11",
    displayDate: "Nov 2026",
    title: "Ink Spiral: Symbolic Transformation from The Thinker to the Four Gentlemen",
    authors: "Lingyu Peng, Wenbo Lu, Liying Long, and Qingchuan Li",
    venue: "Forthcoming · ACM Multimedia 2026, Interactive Art · November 2026",
    links: [
      { label: "Paper", href: "https://arxiv.org/abs/2605.11816" },
      { label: "Video", href: "https://player.vimeo.com/video/1137178061" },
    ],
    teaser: "portfolio/ink-spiral.png",
    keywords: ["Generative AI", "Ink art", "Cross-cultural symbolism", "Video installation"],
    abstract: "Ink Spiral connects Western rational contemplation with Eastern ideas of moral and spiritual cultivation. Across thousands of AI-generated ink frames, a rotating figure inspired by The Thinker transforms into plum, orchid, bamboo, and chrysanthemum, creating a fluid dialogue between sculpture and ink, introspection and nature.",
    project: "ink-spiral",
    featured: true,
  },
  {
    id: "A03",
    category: "Art Papers",
    year: "2026",
    date: "2026-11",
    displayDate: "Nov 2026",
    title: "COSMIC 1001: Engaging Future Speculation on Space Exploration with Generative AI",
    authors: "Lingyu Peng, Yu Liang, Ying Zhang, Chang Ge, and Qingchuan Li",
    venue: "Forthcoming · ACM Multimedia 2026, Interactive Art · November 2026",
    links: [
      { label: "Paper", href: "https://arxiv.org/abs/2605.11827" },
      { label: "Video", href: "https://player.vimeo.com/video/1185854585" },
    ],
    teaser: "portfolio/cosmic.png",
    keywords: ["Speculative design", "Space exploration", "Generative AI", "Interactive installation"],
    abstract: "COSMIC 1001 turns the history of space exploration into a speculative news experience. Visitors browse past events, pose future-oriented questions, and receive AI-generated news stories that accumulate in a shared Future Tunnel, making possible futures visible and open to collective discussion.",
    project: "cosmic",
    featured: true,
  },
  {
    id: "A04",
    category: "Art Papers",
    year: "2025",
    date: "2025-11",
    displayDate: "Nov 2025",
    title: "Tides of Memory: Digital Echoes of Netizen Remembrance",
    authors: "Lingyu Peng, Chang Ge, Liying Long, Xin Li, Xiao Hu, Pengda Lu, Qingchuan Li, and Jiangyue Wu",
    venue: "IEEE VIS Arts Program, 2025",
    links: [
      { label: "Paper", href: "https://ieeexplore.ieee.org/abstract/document/11299026" },
      { label: "Video", href: "https://www.youtube.com/watch?v=QS9Fz3DPeKc" },
    ],
    teaser: "portfolio/tides.png",
    keywords: ["Digital mourning", "Collective memory", "Artistic visualization", "Digital humanities"],
    abstract: "This interactive installation visualizes collective mourning on Sina Weibo after the deaths of seven Chinese authors. It combines text analysis, engagement data, and 3D modeling to transform dispersed online remembrance into an immersive landscape of digital monuments and collective memory.",
    project: "tides",
    featured: true,
  },
];

export const projects = [
  {
    id: "tides",
    title: "Tides of Memory",
    subtitle: "Digital Echoes of Netizen Remembrance",
    year: "2025",
    date: "2025-07",
    displayDate: "Jul 2025",
    image: "portfolio/tides.png",
    type: "Artistic Visualization · Interactive Installation",
    description: "An interactive artwork that transforms online mourning for seven Chinese authors into immersive digital monuments. Text analysis, engagement data, and 3D forms come together to materialize collective memory in the digital age.",
    link: "https://www.youtube.com/watch?v=QS9Fz3DPeKc",
  },
  {
    id: "ink-spiral",
    title: "Ink Spiral",
    subtitle: "From The Thinker to the Four Gentlemen",
    year: "2025",
    date: "2025-05",
    displayDate: "May 2025",
    image: "portfolio/ink-spiral.png",
    type: "Generative AI · Video Installation",
    description: "A video installation connecting Western rational contemplation with Eastern philosophical aesthetics. AI-generated ink imagery transforms The Thinker into plum, orchid, bamboo, and chrysanthemum across a continuous visual spiral.",
    link: "https://player.vimeo.com/video/1137178061",
  },
  {
    id: "kawaii-filter",
    title: "KAWAII FILTER STUDIO",
    subtitle: "Create a face filter from your own drawings",
    year: "2026",
    date: "2026-04",
    displayDate: "Apr 2026",
    image: "portfolio/kawaii-filter.png",
    type: "Interactive Web Experience",
    description: "A playful web experience for creating personalized social-media face filters. Visitors can draw directly or upload hand-drawn materials, animate the visual elements, and turn them into dynamic effects for portrait photography.",
    link: "https://diy-face-filter-studio-352331414026.us-west1.run.app/",
  },
  {
    id: "cosmic",
    title: "COSMIC 1001",
    subtitle: "Speculative futures of space exploration",
    year: "2026",
    date: "2026-04",
    displayDate: "Apr 2026",
    image: "portfolio/cosmic.png",
    type: "Generative AI · Interactive Installation",
    description: "An interactive installation that turns space exploration history into a speculative news experience. Visitors generate future stories that accumulate in a shared tunnel of possible futures.",
    link: "https://player.vimeo.com/video/1185854585",
  },
  {
    id: "yun",
    title: "Yun: Dynamic Ink Landscape",
    subtitle: "An embodied interpretation of ink painting",
    year: "2024",
    date: "2024-09",
    displayDate: "Sep 2024",
    image: "portfolio/yun.png",
    type: "Embodied Interaction · Interactive Installation",
    description: "An embodied artwork rooted in the Chinese ink-painting concept of Yun. Movement and physiological data shape a dynamic landscape where body, emotion, traditional aesthetics, and computation converge.",
    link: "https://player.vimeo.com/video/1137176999",
  },
  {
    id: "beyond-mbti",
    title: "Beyond MBTI",
    subtitle: "A dynamic view of personality",
    year: "2024",
    date: "2024-05",
    displayDate: "May 2024",
    image: "portfolio/beyond-mbti.png",
    type: "Artistic Visualization · Interactive Installation",
    description: "An interactive data artwork that challenges fixed personality categories. It represents personality traits as evolving visual symbols, encouraging a more fluid understanding of identity and self-perception.",
    link: "https://yu-s-design-portfolio-352331414026.us-west1.run.app",
  },
];
